name: Platform Infrastructure

on:
  push:
    paths:
      - platform/**
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: platform

    steps:
      - name: Checkout 
        uses: actions/checkout@v3
      
      - name: Terraform init
        run: |
          terraform init
        shell: bash
        env:
          TF_VAR_environment: "test"
          GOOGLE_CREDENTIALS: ${{ secrets.GCPCRED }}
      
      - name: Terraform apply
        run: |
          terraform apply --auto-approve
        shell: bash
        env:
          TF_VAR_environment: "test"
          GOOGLE_CREDENTIALS: ${{ secrets.GCPCRED }}
