name: Platform Infrastructure

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment'
        required: true
        default: "test"
  push:
    paths:
      - platform/**
    branches: [ "main" ]

env:
  TF_VAR_environment: '${{ github.event.inputs.environment }}'
  GOOGLE_CREDENTIALS: ${{ secrets.GCPCRED }}

jobs:
  step1:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: platform/step1

    steps:
      - name: Checkout 
        uses: actions/checkout@v3

      - name: Terraform init
        run: |
          terraform init
        shell: bash

      - name: Terraform apply
        run: |
          terraform apply --auto-approve
        shell: bash

  step2:
    needs: [step1]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: platform/step2

    steps:
      - name: Checkout 
        uses: actions/checkout@v3
      
      - name: Terraform init
        run: |
          terraform init
        shell: bash

      - name: Terraform apply
        run: |
          terraform apply --auto-approve
        shell: bash

  step3:
    needs: [step2]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: platform/step3

    steps:
      - name: Checkout 
        uses: actions/checkout@v3
      
      - name: Terraform init
        run: |
          terraform init
        shell: bash
      
      - name: Terraform apply
        run: |
          terraform apply --auto-approve
        shell: bash
